# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bryan Stern
tagline:          'A chronicle of my nerdy adventures'
description:      'A chronicle of my nerdy adventures'
url:              http://bryanstern.github.io

author:
  name:           'Bryan Stern'
  url:            https://twitter.com/bryanstern

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bryanstern/bryanstern.github.io

contact:
  twitter:		  http://twitter.com/bryanstern
  linkedin:		  http://www.linkedin.com/in/bryanstern
  github:		  http://github.com/bryanstern
